version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build: ../../auth-service
    ports:
      - "8081:8080"
  customer-service:
    build: ../../customer-service
    ports:
      - "8082:8080"
  account-service:
    build: ../../account-service
    ports:
      - "8083:8080"
  transfer-service:
    build: ../../transfer-service
    ports:
      - "8084:8080"
  wallet-service:
    build: ../../wallet-service
    ports:
      - "8085:8080"

volumes:
  postgres_data:
