quarkus.http.port=0
quarkus.http.test-port=0
quarkus.log.console.json=true
quarkus.smallrye-openapi.info-title=transfer-service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/transferdb
quarkus.datasource.username=bank_user
quarkus.datasource.password=bank_pass
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
kafka.bootstrap.servers=localhost:9092
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.transfer-completed-out.connector=smallrye-kafka
mp.messaging.outgoing.transfer-completed-out.topic=transfer.completed.v1
mp.messaging.outgoing.transfer-completed-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
