quarkus.http.port=0
quarkus.http.test-port=0
quarkus.log.console.json=true
quarkus.smallrye-openapi.info-title=account-service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/accountdb
quarkus.datasource.username=bank_user
quarkus.datasource.password=bank_pass
quarkus.hibernate-orm.database.generation=none
kafka.bootstrap.servers=localhost:9092
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
